[package]
name = "input"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "input"
path = "src/main.rs"

[dependencies]
redpowder = { path = "../../redpowder" }

[profile.release]
panic = "abort"
opt-level = 2
lto = false
codegen-units = 1
debug = 2
strip = "none"
